# Generated by Django 4.1.7 on 2023-11-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(max_length=40)),
                ('Numero', models.IntegerField()),
                ('Horas', models.IntegerField()),
            ],
        ),
    ]
