# Generated by Django 4.1.7 on 2023-11-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
